export enum IpcEvents {
  CLICK_TITLEBAR_MAC = "CLICK_TITLEBAR_MAC",

  GET_APPEARANCE = "GET_APPEARANCE",
  CHANGE_APPEARANCE = "CHANGE_APPEARANCE",

  GET_LANGUAGES = "GET_LANGUAGES",
  TOGGLE_LANGUAGE = "TOGGLE_LANGUAGE",
  CHANGED_LANGUAGE_SET = "CHANGED_LANGUAGE_SET",
}
